spring:
  datasource:
    url: "jdbc:h2:mem:testdb" # URL of the DB
    driver-class-name: "org.h2.Driver" # Use H2 in-memory DB
    username: "sa"
    password: ""
  h2:
    console:
      enabled: "true" # Visit /h2-console to access Admin console of H2
